version: '3'
services:
    mysql:
      container_name: db
      image: mariadb:10.4
      restart: always
      volumes:
        - ./mysql/db/initdb/:/docker-entrypoint-initdb.d
        - ./mysql/db/data/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=test1234
        - MYSQL_DATABASE=studentgroupingsystem

      ports: 
        - 3306:3306
      networks: 
        - default

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5
      restart: always
      ports:
      - 8080:80
      environment:
        PMA_HOST: mysql

    
    web:
      container_name: web
      image: nginx:alpine
      volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/groupset.conf:/etc/nginx/conf.d/groupset.conf
        - ./nginx/ssl/conf:/etc/nginx/ssl/:ro
        - ./web:/var/www/html
      ports:
        - 80:80  #http
        - 443:443 #https
      
      networks: 
        - default
      restart: always

    certbot:
      image: certbot/certbot:latest
      volumes:
      - ./web:/var/www/html:rw
      - ./nginx/ssl/conf/:/etc/letsencrypt/:rw

      # http://groupset.org
      # dns point to IP server
      # req ssl to certbot server > check dns/IP server/website accessble


    php:
      build: './php/'
      container_name: php-fpm
      restart: always
      volumes:
        - ./web:/var/www/html
        - ./logs/php-fpm:/var/log/php-fpm
        - ./php/php.ini:/etc/php/php
      expose:
        - "9000"
      
networks:
  default:
    external:
      name: web_network
