version: '3'
services:
    mysql:
      container_name: db
      image: mariadb:10.4
      restart: always
      volumes:
        - ./mysql/db/initdb/:/docker-entrypoint-initdb.d
        - ./mysql/db/data/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=test1234
        - MYSQL_DATABASE=studentgroupingsystem

      ports: 
        - 3306:3306
      networks: 
        - default

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5
      restart: always
      ports:
      - 8080:80
      environment:
        PMA_HOST: mysql

    
    web:
      container_name: web
      image: nginx:alpine
      volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/groupset.conf:/etc/nginx/conf.d/groupset.conf
      #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/ssl/:/etc/nginx/ssl
        - ./web:/var/www/html
      ports:
        - 80:80
        - 443:443
      
      networks: 
        - default
      restart: always

    php:
      build: './php/'
      container_name: php-fpm
      restart: always
      volumes:
        - ./web:/var/www/html
        - ./logs/php-fpm:/var/log/php-fpm
        - ./php/php.ini:/etc/php/php
      expose:
        - "9000"
      

networks:
  default:
    external:
      name: web_network